import React, { useEffect, useState } from 'react';
import { ArrowLeft, ChevronRight, Compass, Radio, Shield, Sparkles, Users } from 'lucide-react';
import { factionAPI } from '../services/api';
import { User } from '../types';

type FactionSummary = {
  key:string; name:string; color:string; tagline:string; description:string; motto:string; memberCount:number;
  relationship:'visitor'|'member'|'other_faction'|'unaffiliated';
  progression:{state:'available';total:number;updatedAt:string}|{state:'unavailable'};
};
type FactionDetail = FactionSummary & { members:any[]; activity:any[]; announcements:any[] };

const Relationship = ({ value }:{value:FactionSummary['relationship']}) => {
  const text = value === 'member' ? 'Your faction' : value === 'unaffiliated' ? 'Open to independent members' : value === 'other_faction' ? 'Cross-faction view' : 'Public faction';
  return <span className="inline-flex items-center gap-1 border border-current/30 px-2 py-1 text-[10px] uppercase tracking-[.16em]"><Shield size={11}/>{text}</span>;
};

const State = ({ faction }:{faction:FactionSummary}) => <div className="border border-white/10 bg-black/35 p-4">
  <p className="text-[10px] uppercase tracking-[.2em] text-gray-500">Faction overall state</p>
  {faction.progression.state === 'available' ? <><p className="mt-2 text-2xl font-black text-white tabular-nums">{faction.progression.total}</p><p className="text-xs text-gray-400">Combined legitimate member contribution. This is distinct from personal progression.</p></> : <><p className="mt-2 text-sm text-gray-300">Awaiting canonical projection</p><p className="mt-1 text-xs text-gray-500">No score is inferred or fabricated.</p></>}
</div>;

const FactionsPage:React.FC<{currentUser:User; factionKey?:string|null; onOpen:(key:string)=>void; onBack:()=>void; onUserClick:(username:string)=>void}> = ({currentUser,factionKey,onOpen,onBack,onUserClick}) => {
  const [list,setList]=useState<FactionSummary[]>([]); const [detail,setDetail]=useState<FactionDetail|null>(null); const [state,setState]=useState<'loading'|'ready'|'error'>('loading');
  useEffect(()=>{let active=true;setState('loading');const call=factionKey?factionAPI.get(factionKey):factionAPI.list();call.then(({data})=>{if(active){if(factionKey)setDetail(data.data);else setList(data.data||[]);setState('ready')}}).catch(()=>active&&setState('error'));return()=>{active=false}},[factionKey]);
  if(state==='loading')return <div className="min-h-full grid place-items-center text-xs tracking-widest text-gray-500">TUNING FACTION SIGNALS…</div>;
  if(state==='error')return <div className="mx-auto max-w-xl p-8 text-center"><p className="text-white">Faction signal unavailable.</p><button onClick={onBack} className="mt-4 text-xs text-[#39FF14]">RETURN</button></div>;
  if(!factionKey)return <div className="mx-auto max-w-7xl px-4 py-8 md:px-8 md:py-12">
    <header className="mb-8 grid gap-5 md:grid-cols-[1fr_auto] md:items-end"><div><p className="text-xs uppercase tracking-[.28em] text-[#39FF14]">Identity network</p><h1 className="mt-2 text-3xl md:text-5xl font-black text-white">CyberDope Factions</h1><p className="mt-3 max-w-2xl text-sm text-gray-400">Browse the founding communities, their public activity, and their shared progression. Membership is never required.</p></div>{currentUser.faction==='Unaffiliated'&&<div className="max-w-sm border border-dashed border-white/20 bg-white/[.03] p-4"><p className="font-bold text-white">Independent by choice</p><p className="mt-1 text-xs text-gray-400">Your personal progression, social graph, and discovery access stand on their own. Explore every faction without joining one.</p></div>}</header>
    <div data-testid="faction-directory" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{list.map(f=><button key={f.key} onClick={()=>onOpen(f.key)} className="group min-h-48 border bg-black/60 p-5 text-left transition-transform hover:-translate-y-0.5" style={{borderColor:`${f.color}66`,boxShadow:`inset 0 3px 0 ${f.color}`}}><div className="flex items-start justify-between gap-3"><div className="h-10 w-10 grid place-items-center border" style={{color:f.color,borderColor:f.color}}><Radio size={18}/></div><Relationship value={f.relationship}/></div><h2 className="mt-6 text-xl font-black text-white">{f.name}</h2><p className="mt-1 text-[10px] font-bold tracking-[.14em]" style={{color:f.color}}>{f.tagline}</p><div className="mt-4 flex items-center justify-between text-xs text-gray-500"><span>{f.memberCount} {f.memberCount===1?'member':'members'}</span><ChevronRight className="transition-transform group-hover:translate-x-1" size={16}/></div></button>)}</div>
  </div>;
  if(!detail)return null;
  return <div style={{'--faction-color':detail.color} as React.CSSProperties} className="min-h-full bg-[radial-gradient(circle_at_top,color-mix(in_srgb,var(--faction-color)_15%,transparent),transparent_45%)]">
    <div className="mx-auto max-w-6xl px-4 py-6 md:px-8 md:py-10"><button onClick={onBack} className="mb-5 inline-flex items-center gap-2 text-xs uppercase tracking-widest text-gray-400 hover:text-white"><ArrowLeft size={15}/>All factions</button>
      <header data-testid="faction-destination" className="border p-5 md:p-8" style={{borderColor:`${detail.color}66`,boxShadow:`inset 0 4px 0 ${detail.color}`}}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold tracking-[.18em]" style={{color:detail.color}}>{detail.tagline}</p><h1 className="mt-2 text-4xl md:text-6xl font-black text-white">{detail.name}</h1></div><Relationship value={detail.relationship}/></div><p className="mt-5 max-w-3xl text-gray-300">{detail.description}</p>{detail.motto&&<p className="mt-4 text-xs font-black tracking-[.2em] text-white">{detail.motto}</p>}</header>
      <div className="mt-5 grid gap-5 lg:grid-cols-[1.5fr_.75fr]"><div className="space-y-5"><section className="border border-white/10 bg-black/50 p-5"><div className="flex items-center gap-2"><Sparkles size={17} style={{color:detail.color}}/><h2 className="font-bold text-white">Recent faction activity</h2></div>{detail.activity.length?<div className="mt-4 space-y-3">{detail.activity.map(post=><article key={post._id} className="border border-white/10 p-4"><button onClick={()=>onUserClick(post.author.username)} className="text-xs font-bold hover:underline" style={{color:detail.color}}>@{post.author.username}</button><p className="mt-2 text-sm text-gray-300 line-clamp-3">{post.title||post.content||post.description}</p><time className="mt-2 block text-[10px] text-gray-600">{new Date(post.createdAt).toLocaleDateString()}</time></article>)}</div>:<p className="mt-4 text-sm text-gray-500">No public or authorized faction activity yet.</p>}</section>
      </div><aside className="space-y-5"><State faction={detail}/><section className="border border-white/10 bg-black/35 p-4"><div className="flex items-center gap-2"><Users size={16} style={{color:detail.color}}/><h2 className="font-bold text-white">Community</h2></div><p className="mt-1 text-xs text-gray-500">{detail.memberCount} active {detail.memberCount===1?'member':'members'}</p><div className="mt-4 grid grid-cols-4 gap-2">{detail.members.slice(0,12).map(member=><button key={member._id} onClick={()=>onUserClick(member.username)} title={member.displayName||member.username} className="aspect-square overflow-hidden border border-white/10 bg-white/5"><img src={member.avatar||`https://api.dicebear.com/7.x/avataaars/svg?seed=${member.username}`} alt={member.username} className="h-full w-full object-cover"/></button>)}</div>{!detail.members.length&&<p className="mt-4 text-xs text-gray-500">No publicly listed members yet.</p>}</section><section className="border border-white/10 bg-black/35 p-4"><h2 className="font-bold text-white">Announcements</h2>{detail.announcements.length?<div className="mt-3 space-y-3">{detail.announcements.map(a=><div key={a._id}>{a.title&&<p className="text-sm font-bold text-white">{a.title}</p>}<p className="text-sm text-gray-300">{a.message}</p><time className="text-[10px] text-gray-600">{new Date(a.createdAt).toLocaleDateString()}</time></div>)}</div>:<p className="mt-3 text-xs text-gray-500">No active announcements. Check recent activity for the latest public signal.</p>}</section></aside></div>
    </div></div>;
};
export default FactionsPage;
