import React, { useEffect, useMemo, useState } from 'react';
import { Activity, Aperture, Bot, ChevronRight, Circle, Eye, Hexagon, Radio, Send, Shield, Sparkles } from 'lucide-react';
import { outriderAPI } from '../services/api';
import { User } from '../types';

const tint = ['#56f7ff', '#ff4fd8', '#a8ff60', '#ffb347', '#9b7bff'];
const ago = (value: string) => { const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); return seconds < 60 ? `${seconds}s` : seconds < 3600 ? `${Math.floor(seconds / 60)}m` : `${Math.floor(seconds / 3600)}h`; };

const OutriderGlass: React.FC<{ user: User }> = ({ user }) => {
  const [world, setWorld] = useState<any>(null); const [operator, setOperator] = useState<any>(null);
  const [spaceId, setSpaceId] = useState('outrider-hub'); const [agentId, setAgentId] = useState('guide-lumen');
  const [message, setMessage] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const refresh = async () => { const { data } = await outriderAPI.snapshot(); setWorld(data.world); if (user.isAdmin) { try { setOperator((await outriderAPI.operatorStatus()).data.operator); } catch {} } };
  useEffect(() => { void refresh(); const id = window.setInterval(() => void refresh(), 6000); return () => clearInterval(id); }, []);
  useEffect(() => { void outriderAPI.enter(spaceId).catch(() => undefined); }, [spaceId]);
  const space = world?.spaces?.find((x: any) => x.spaceId === spaceId) || world?.spaces?.[0];
  const agents = useMemo(() => (world?.agents || []).filter((x: any) => x.currentSpaceId === space?.spaceId), [world, space]);
  const selected = world?.agents?.find((x: any) => x.agentId === agentId);
  const events = (world?.events || []).filter((x: any) => x.spaceId === space?.spaceId);
  const send = async () => { if (!message.trim() || !selected) return; setBusy(true); try { const { data } = await outriderAPI.address(space.spaceId, selected.agentId, message); setMessage(''); setNotice(data.runtimeError ? `Signal entered the world; response deferred (${data.runtimeError}).` : `${selected.displayIdentity.name} perceived your signal.`); await refresh(); } catch (error: any) { setNotice(error.response?.data?.message || 'Outrider rejected the signal.'); } finally { setBusy(false); } };
  if (!world) return <div className="h-full grid place-items-center bg-[#020508] text-cyan-300"><Aperture className="animate-spin" /><span className="tracking-[.4em] text-xs">CALIBRATING OUTRIDER</span></div>;
  return <div className="h-full overflow-y-auto bg-[#020508] text-slate-100 relative" style={{backgroundImage:'radial-gradient(circle at 42% 18%,rgba(36,211,238,.12),transparent 32%),linear-gradient(rgba(86,247,255,.025) 1px,transparent 1px),linear-gradient(90deg,rgba(86,247,255,.025) 1px,transparent 1px)',backgroundSize:'auto,34px 34px,34px 34px'}}>
    <div className="sticky top-0 z-20 border-b border-cyan-300/15 bg-[#020508]/85 backdrop-blur-xl px-4 md:px-7 py-4 flex items-center justify-between"><div><div className="flex items-center gap-3"><Eye className="text-cyan-300"/><h2 className="text-2xl tracking-[.35em] font-light">OUTRIDER</h2><span className="text-[9px] px-2 py-1 rounded-full border border-amber-300/30 text-amber-200">STAGING WORLD</span></div><p className="text-[10px] text-slate-500 tracking-[.22em] mt-1">OBSERVE · DO NOT COMMAND</p></div><div className="flex items-center gap-2 text-xs text-emerald-300"><Radio size={14} className="animate-pulse"/><span>{world.status.toUpperCase()}</span><span className="text-slate-600">{world.events.length} SIGNALS</span></div></div>
    <div className="grid xl:grid-cols-[250px_minmax(0,1fr)_340px] min-h-[calc(100vh-8rem)]">
      <aside className="border-r border-cyan-300/10 p-4 space-y-3"><p className="text-[10px] tracking-[.3em] text-slate-500 mb-4">VISIBLE TERRITORIES</p>{world.spaces.map((item:any,index:number)=><button key={item.spaceId} onClick={()=>setSpaceId(item.spaceId)} className={`w-full text-left p-3 rounded-xl border transition ${space?.spaceId===item.spaceId?'bg-cyan-300/10 border-cyan-300/40':'bg-white/[.02] border-white/[.06] hover:border-white/20'}`}><div className="flex items-center gap-2"><Hexagon size={15} style={{color:tint[index%tint.length]}}/><span className="text-sm">{item.name}</span><span className="ml-auto text-[10px] text-slate-500">{item.presentAgentIds.length}</span></div><p className="text-[10px] text-slate-500 mt-2 line-clamp-2">{item.description}</p></button>)}
        {user.isAdmin && operator && <div className="mt-6 p-3 rounded-xl border border-fuchsia-400/20 bg-fuchsia-400/[.04]"><div className="flex items-center gap-2 text-fuchsia-300 text-xs"><Shield size={14}/>OPERATOR LENS</div><div className="mt-3 grid grid-cols-2 gap-2 text-[10px]"><span>RUNTIME</span><span className={operator.controls.runtimeEnabled?'text-emerald-300':'text-red-300'}>{operator.controls.runtimeEnabled?'ENABLED':'KILLED'}</span><span>MODEL</span><span className="truncate text-cyan-200">{operator.runtime.provider}</span><span>TICKS</span><span>{operator.executions.length}</span><span>DENIALS</span><span>{operator.denials.length}</span></div></div>}
      </aside>
      <section className="p-4 md:p-7 min-w-0"><div className="flex items-end justify-between mb-6"><div><p className="text-[10px] tracking-[.3em] text-cyan-300/60">CURRENT SPACE</p><h3 className="text-3xl md:text-5xl font-light mt-1">{space?.name}</h3><p className="text-sm text-slate-500 mt-2">{space?.description}</p></div><Activity className="text-cyan-300/30" size={38}/></div>
        <div className="relative min-h-[240px] rounded-3xl border border-cyan-300/10 bg-black/30 overflow-hidden p-6"><div className="absolute inset-0 opacity-30" style={{background:'radial-gradient(circle at center,rgba(86,247,255,.18),transparent 55%)'}}/><div className="relative flex flex-wrap justify-around gap-8 py-8">{agents.map((agent:any,index:number)=><button key={agent.agentId} onClick={()=>setAgentId(agent.agentId)} className="group flex flex-col items-center gap-3"><div className={`w-20 h-20 rounded-full grid place-items-center border ${agentId===agent.agentId?'border-cyan-200 shadow-[0_0_35px_rgba(86,247,255,.35)]':'border-white/20'} bg-black/70 group-hover:scale-105 transition`}><Bot style={{color:tint[index%tint.length]}}/></div><div className="text-sm">{agent.displayIdentity.name}</div><div className="flex items-center gap-1 text-[9px] text-emerald-300"><Circle size={6} fill="currentColor"/>PRESENT</div></button>)}</div></div>
        <div className="mt-6"><div className="flex items-center gap-2 text-xs tracking-[.25em] text-slate-400 mb-3"><Activity size={14}/>WORLD ACTIVITY</div><div className="space-y-2">{events.slice(0,12).map((event:any)=><button key={event.eventId} className="w-full text-left p-3 border-l border-cyan-300/30 bg-white/[.025] hover:bg-white/[.045]"><div className="flex gap-3 text-xs"><span className="text-cyan-300">{event.eventType.replaceAll('.',' / ')}</span><span className="ml-auto text-slate-600">{ago(event.occurredAt)}</span></div><p className="text-sm text-slate-400 mt-1">{event.payload?.text || event.payload?.data?.milestone || event.payload?.subject?.type || 'A state change rippled through the world.'}</p></button>)}</div></div>
      </section>
      <aside className="border-l border-cyan-300/10 p-4 md:p-5 bg-black/20"><p className="text-[10px] tracking-[.3em] text-slate-500">PRESENCE INSPECTOR</p>{selected?<><div className="my-5 p-5 rounded-2xl bg-gradient-to-br from-cyan-300/10 to-fuchsia-400/5 border border-cyan-300/20"><Bot className="text-cyan-300 mb-4"/><h4 className="text-xl">{selected.displayIdentity.name}</h4><p className="text-xs text-slate-400 mt-2">{selected.displayIdentity.description}</p><div className="mt-4 text-[10px] text-slate-500">{selected.agentType.toUpperCase()} · {selected.factionId?'FACTION SIGNAL':'INDEPENDENT'}</div></div><div className="space-y-2"><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder={`Cast a signal into ${selected.displayIdentity.name}'s world…`} className="w-full h-24 resize-none rounded-xl bg-black/70 border border-white/10 p-3 text-sm outline-none focus:border-cyan-300/50"/><button onClick={send} disabled={busy||!message.trim()} className="w-full rounded-xl bg-cyan-300 text-black py-3 text-xs tracking-[.2em] font-bold disabled:opacity-40 flex items-center justify-center gap-2"><Send size={14}/>{busy?'TRANSMITTING':'ADDRESS WORLD'}</button>{notice&&<p className="text-[11px] text-cyan-200/70 py-2">{notice}</p>}</div></>:<p className="mt-5 text-sm text-slate-500">Select a presence.</p>}
        <div className="mt-8"><p className="text-[10px] tracking-[.3em] text-slate-500 mb-3">ARTIFACTS</p>{world.artifacts.slice(0,8).map((a:any)=><div key={a.artifactId} className="p-3 border border-white/[.07] rounded-xl mb-2"><div className="flex gap-2 text-xs"><Sparkles size={13} className="text-fuchsia-300"/>{a.title}</div><p className="text-[10px] text-slate-600 mt-2">BY {a.creatorAgentId}</p></div>)}</div>{operator?.proposals?.length>0&&<div className="mt-8"><p className="text-[10px] tracking-[.3em] text-slate-500 mb-3">OUTRIDER PROPOSALS</p>{operator.proposals.slice(0,4).map((p:any)=><div key={p.proposalId} className="p-3 border border-amber-300/20 rounded-xl mb-2 text-xs"><div className="flex items-center">{p.agentId}<ChevronRight size={12} className="ml-auto"/></div><div className="text-amber-200 mt-2">{p.status.replaceAll('_',' ').toUpperCase()}</div></div>)}</div>}
      </aside>
    </div>
  </div>;
};
export default OutriderGlass;
