import React from 'react';
import { BadgeCheck, ExternalLink, Image, Lock, Radio, Sparkles, Users } from 'lucide-react';
import TopFriendsWidget from './TopFriendsWidget';

export interface ProfileV2Module { _id: string; type: string; position: number; config?: Record<string, any>; locked?: boolean; presentation?: string; accessRule?: string | null }
const requirementLabel = (node:any):string => { if(!node)return 'restricted access'; if(node.op==='predicate')return ({everyone:'Public',authenticated:'CyberDope users',followers:'Followers',friends:'Friends',same_faction:'Same faction',age_verified:'Age verified',subscribers:'Subscriber',creator_tier:'Membership tier',owner:'Only you'} as Record<string,string>)[node.type]||'Requirement'; return (node.children||[]).map((child:any)=>child.op&&['and','or'].includes(child.op)?`(${requirementLabel(child)})`:requirementLabel(child)).join(node.op==='and'?' AND ':' OR '); };
const shell='profile-v2-card border bg-black/70 backdrop-blur-md';

const Identity=({owner,config}:any)=><section data-module="identity" className={`${shell} overflow-hidden`}>{owner.banner&&<img src={owner.banner} alt="" className="profile-hero-banner h-32 md:h-52 w-full object-cover"/>}<div className="profile-hero-body p-5 md:p-7 flex items-end gap-4 -mt-10 relative"><img src={owner.avatar} alt={`${owner.username}'s avatar`} className="h-24 w-24 md:h-28 md:w-28 rounded-[var(--profile-radius)] object-cover border-4 border-black"/><div className="pb-1 min-w-0"><h1 className="text-2xl md:text-4xl font-black text-white truncate">{owner.displayName||owner.username}</h1><p style={{color:'var(--profile-primary)'}}>@{owner.username} {owner.isVerified&&<BadgeCheck className="inline" size={16}/>}</p>{config?.tagline&&<p className="text-sm text-gray-300 mt-1">{config.tagline}</p>}</div></div></section>;
const Bio=({owner,config}:any)=><section data-module="bio" className={`${shell} p-5 md:p-7`}><p className="profile-kicker">Signal</p><h2>About</h2><p className="text-gray-300 whitespace-pre-wrap mt-3 max-w-3xl leading-relaxed">{config?.text||owner.bio||'This signal has not been written yet.'}</p>{owner.location&&<p className="text-xs text-gray-500 mt-3">{owner.location}</p>}</section>;
const Faction=({owner}:any)=><section data-module="faction" className={`${shell} p-5 relative overflow-hidden`}><Radio className="absolute right-4 top-4 opacity-20" size={70}/><p className="profile-kicker">Faction identity</p><h2 style={{color:'var(--profile-primary)'}}>{owner.faction||'Unaffiliated'}</h2><p className="text-sm text-gray-400 mt-2">Your culture, on your terms.</p></section>;
const Posts=({posts}:any)=><section data-module="posts" className={`${shell} p-5 md:p-7`}><p className="profile-kicker">Transmission archive</p><h2>Posts <span className="text-gray-500">{posts.length}</span></h2><div className="grid grid-cols-2 md:grid-cols-3 gap-2 mt-4">{posts.slice(0,9).map((post:any)=><article key={post._id} className="aspect-square border border-white/10 overflow-hidden bg-black/50">{post.thumbnailUrl||post.mediaUrl?<img src={post.thumbnailUrl||post.mediaUrl} alt={post.title||'Post'} className="w-full h-full object-cover"/>:<p className="p-3 text-xs text-gray-300 line-clamp-6">{post.description||post.content}</p>}</article>)}</div>{!posts.length&&<p className="text-gray-500 text-sm mt-4">No transmissions published.</p>}</section>;
const Media=({posts,config}:any)=>{const media=posts.filter((post:any)=>post.mediaUrl).slice(0,config?.limit||6);return <section data-module="media" className={`${shell} p-5`}><p className="profile-kicker">Gallery</p><h2><Image className="inline mr-2" size={18}/>Media</h2><div className="grid grid-cols-3 gap-2 mt-4">{media.map((post:any)=><img key={post._id} src={post.thumbnailUrl||post.mediaUrl} alt="Gallery item" className="w-full aspect-square object-cover"/>)}</div>{!media.length&&<p className="text-gray-500 text-sm mt-4">No media selected yet.</p>}</section>};
const Links=({owner}:any)=>{const links=Object.entries(owner.socialLinks||{}).filter(([,value])=>value);return <section data-module="links" className={`${shell} p-5`}><p className="profile-kicker">Elsewhere</p><h2>Links</h2><div className="flex flex-wrap gap-2 mt-4">{owner.website&&<a href={owner.website} target="_blank" rel="noreferrer" className="profile-chip">Website <ExternalLink size={12}/></a>}{links.map(([name,url])=><a key={name} href={String(url)} target="_blank" rel="noreferrer" className="profile-chip">{name}</a>)}</div>{!owner.website&&!links.length&&<p className="text-gray-500 text-sm mt-3">No external links.</p>}</section>};
const Creator=({owner,config,posts}:any)=>{const featured=posts.filter((post:any)=>post.mediaUrl||post.thumbnailUrl).slice(0,3);return <section data-module="creator_summary" className={`${shell} profile-creator p-5 md:p-8 overflow-hidden relative`}><Sparkles className="absolute right-6 top-6 opacity-20" size={88}/><div className="relative grid md:grid-cols-[1.2fr_.8fr] gap-6 items-end"><div><p className="profile-kicker">Creator signal</p><h2 className="!text-2xl md:!text-3xl">{config?.heading||`${owner.displayName||owner.username} creates here`}</h2><p className="text-gray-300 mt-3 max-w-xl leading-relaxed">{config?.description||owner.creatorBio||'Original work, selected releases, and the story behind the signal.'}</p><div className="flex flex-wrap gap-2 mt-5"><span className="profile-chip"><Users size={13}/> Follow the work</span>{owner.website&&<a href={owner.website} target="_blank" rel="noreferrer" className="profile-chip">Creator links <ExternalLink size={12}/></a>}</div><p className="text-[10px] uppercase tracking-widest text-gray-500 mt-4">Paid memberships are not available yet</p></div><div className="grid grid-cols-3 gap-2">{featured.map((post:any)=><img key={post._id} src={post.thumbnailUrl||post.mediaUrl} alt={post.title||'Featured creator work'} className="aspect-[3/4] w-full object-cover border border-white/10"/>)}{!featured.length&&<div className="col-span-3 aspect-[3/1] border border-dashed border-white/15 flex items-center justify-center text-xs text-gray-500">Featured work appears here</div>}</div></div></section>};

export const PROFILE_MODULE_REGISTRY:Record<string,{label:string;description:string;component:React.FC<any>}>= {identity:{label:'Identity / Hero',description:'Avatar, banner, name and tagline',component:Identity},bio:{label:'About',description:'Your personal signal',component:Bio},faction:{label:'Faction',description:'Membership and identity',component:Faction},top_friends:{label:'Top Friends',description:'Your chosen inner circle',component:({userId}:any)=><section data-module="top_friends"><TopFriendsWidget userId={userId}/></section>},posts:{label:'Posts',description:'Published transmissions',component:Posts},media:{label:'Media',description:'Visual archive',component:Media},links:{label:'Links',description:'Safe external destinations',component:Links},creator_summary:{label:'Creator Spotlight',description:'Creator identity and featured work',component:Creator}};
export const ProfileLockedPreview=({module}:{module:ProfileV2Module})=><section data-module="locked" className={`${shell} p-8 text-center`} data-testid="locked-preview"><Lock className="mx-auto mb-3" style={{color:'var(--profile-primary)'}}/><h2>Locked signal</h2><p className="text-xs text-gray-400 mt-2">Requires {requirementLabel((module as any).requirements)}.</p></section>;
const ProfileV2Modules:React.FC<{modules:ProfileV2Module[];userId:string;owner:any;posts?:any[];preview?:boolean}>=({modules,userId,owner,posts=[],preview=false})=><div className="profile-v2-modules" data-testid="profile-v2-modules">{modules.map(module=>{if(module.locked)return <ProfileLockedPreview key={module._id} module={module}/>;const entry=PROFILE_MODULE_REGISTRY[module.type];if(!entry)return null;const Component=entry.component;return <Component key={module._id} module={module} config={module.config||{}} userId={userId} owner={owner} posts={posts} preview={preview}/>})}</div>;
export default ProfileV2Modules;
