import React,{useEffect,useState} from 'react';
import {DndContext,KeyboardSensor,PointerSensor,closestCenter,useSensor,useSensors} from '@dnd-kit/core';
import {SortableContext,arrayMove,sortableKeyboardCoordinates,useSortable,verticalListSortingStrategy} from '@dnd-kit/sortable';
import {CSS} from '@dnd-kit/utilities';
import {GripVertical,Heart,Plus,X} from 'lucide-react';
import {profileAPI,socialAPI} from '../services/api';

const Row=({friend,index,onRemove}:any)=>{const{attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:friend._id});return <div ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition}} className={`flex items-center gap-3 bg-black border border-gray-800 p-2 rounded ${isDragging?'opacity-50':''}`}><button aria-label={`Reorder ${friend.username}`} {...attributes} {...listeners} className="text-gray-500 cursor-grab"><GripVertical size={15}/></button><span className="text-pink-400 font-black">#{index+1}</span><img src={friend.avatar} alt="" className="w-9 h-9 rounded-full object-cover"/><span className="text-white text-sm flex-1 truncate">{friend.displayName||friend.username}</span><button aria-label={`Remove ${friend.username}`} onClick={onRemove} className="text-gray-500 hover:text-red-400"><X size={15}/></button></div>};
const TopFriendsEditor:React.FC=()=>{const[friends,setFriends]=useState<any[]>([]),[selected,setSelected]=useState<any[]>([]),[status,setStatus]=useState('');const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:5}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));useEffect(()=>{Promise.all([socialAPI.getFriends(),profileAPI.getMine()]).then(async([friendsResponse,mine])=>{setFriends(friendsResponse.data?.data||[]);const userId=mine.data?.data?.profile?.user;if(userId){const top=await socialAPI.getTopFriends(userId);setSelected((top.data?.data||[]).map((entry:any)=>entry.friend))}}).catch(()=>setStatus('Could not load accepted friends.'))},[]);const save=async()=>{setStatus('Saving…');try{await socialAPI.setTopFriends(selected.map(friend=>friend._id));setStatus('Top Friends published.');window.dispatchEvent(new Event('topFriendsUpdated'))}catch(error:any){setStatus(error?.response?.data?.message||'Save failed.')}};return <section><div className="flex items-center gap-2 mb-1"><Heart className="text-pink-400 fill-pink-400" size={17}/><h3 className="text-white font-bold">Your Top Friends</h3><span className="ml-auto text-xs text-gray-500">{selected.length}/8</span></div><p className="text-xs text-gray-500 mb-4">An ordered inner circle. Only accepted friends are eligible; blocks and unfriending remove them automatically.</p><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={({active,over})=>{if(over&&active.id!==over.id)setSelected(items=>arrayMove(items,items.findIndex(i=>i._id===active.id),items.findIndex(i=>i._id===over.id)))}}><SortableContext items={selected.map(item=>item._id)} strategy={verticalListSortingStrategy}><div className="space-y-2">{selected.map((friend,index)=><Row key={friend._id} friend={friend} index={index} onRemove={()=>setSelected(items=>items.filter(item=>item._id!==friend._id))}/>)}</div></SortableContext></DndContext>{!selected.length&&<div className="border border-dashed border-gray-800 p-6 text-center text-xs text-gray-500">Your inner circle is empty. Add accepted friends below.</div>}<div className="flex flex-wrap gap-2 mt-4">{friends.filter(friend=>!selected.some(item=>item._id===friend._id)).map(friend=><button key={friend._id} disabled={selected.length>=8} onClick={()=>setSelected(items=>[...items,friend])} className="text-xs border border-gray-700 px-2 py-1 text-gray-300 disabled:opacity-30 rounded"><Plus size={12} className="inline"/> {friend.displayName||friend.username}</button>)}</div><button onClick={save} className="mt-4 px-3 py-2 bg-pink-500 text-black font-bold text-xs rounded">PUBLISH TOP FRIENDS</button>{status&&<p role="status" className="mt-2 text-xs text-gray-300">{status}</p>}</section>};
export default TopFriendsEditor;
