import { test, expect, runtime, userFor } from './fixtures';
import { io } from 'socket.io-client';

test('social, content, comments, DM unread, and creator tiers persist', async ({ request }) => {
  const data = await runtime();
  const auth = async (role: string) => { const user = userFor(data, role); const r = await request.post(`${data.apiURL}/auth/login`, { data: { email: user.email, password: data.password } }); return { user, token: (await r.json()).token }; };
  const primary = await auth('primary'), peer = await auth('peer'), creator = await auth('creator');
  const headers = (token: string) => ({ authorization: `Bearer ${token}` });
  const follow = await request.post(`${data.apiURL}/users/${peer.user.id}/follow`, { headers: headers(primary.token) });
  expect(follow.ok()).toBeTruthy(); expect((await follow.json()).followersCount).toBeGreaterThanOrEqual(0);
  expect((await request.post(`${data.apiURL}/users/${peer.user.id}/follow`, { headers: headers(primary.token) })).ok()).toBeTruthy();
  const post = await request.post(`${data.apiURL}/posts`, { headers: headers(primary.token), data: { type: 'text', content: `E2E ${data.runId}`, description: `E2E ${data.runId}`, visibility: 'public' } });
  expect(post.status()).toBe(201); const postId = (await post.json()).data._id;
  expect((await request.post(`${data.apiURL}/posts/${postId}/like`, { headers: headers(peer.token) })).ok()).toBeTruthy();
  const comment = await request.post(`${data.apiURL}/posts/${postId}/comments`, { headers: headers(peer.token), data: { content: 'deterministic comment' } });
  expect(comment.status()).toBe(201); const commentId = (await comment.json()).data._id;
  expect((await request.post(`${data.apiURL}/posts/${postId}/comments`, { headers: headers(primary.token), data: { content: 'deterministic reply', parentCommentId: commentId } })).status()).toBe(201);
  expect((await request.post(`${data.apiURL}/comments/not-an-id/like`, { headers: headers(primary.token) })).status()).toBe(400);
  expect((await request.get(`${data.apiURL}/search?q=${encodeURIComponent(primary.user.username)}`)).ok()).toBeTruthy();
  const socketOrigin = data.apiURL.replace(/\/api$/, '');
  const peerSocket = io(socketOrigin, { auth: { token: peer.token }, transports: ['websocket'], reconnection: false });
  await new Promise<void>((resolve, reject) => { peerSocket.once('connect', resolve); peerSocket.once('connect_error', reject); });
  const received = new Promise<any>((resolve, reject) => { const timeout = setTimeout(() => reject(new Error('Realtime message timeout')), 5000); peerSocket.once('message', message => { clearTimeout(timeout); resolve(message); }); });
  expect((await request.post(`${data.apiURL}/messages`, { headers: headers(primary.token), data: { recipientId: peer.user.id, content: `realtime ${data.runId}`, isVanishing: false } })).ok()).toBeTruthy();
  expect((await received).content).toBe(`realtime ${data.runId}`);
  peerSocket.disconnect(); peerSocket.connect();
  await new Promise<void>((resolve, reject) => { peerSocket.once('connect', resolve); peerSocket.once('connect_error', reject); });
  peerSocket.disconnect();
  expect((await (await request.get(`${data.apiURL}/messages/unread/count`, { headers: headers(peer.token) })).json()).unreadCount).toBeGreaterThanOrEqual(1);
  const tiers = [{ name: 'QA Tier', price: 3, description: 'persistent', benefits: ['test'], color: 'gray', icon: 'star', isActive: true }];
  expect((await request.put(`${data.apiURL}/creator/subscription-tiers`, { headers: headers(creator.token), data: { tiers } })).ok()).toBeTruthy();
  const fetched = await (await request.get(`${data.apiURL}/creator/subscription-tiers`, { headers: headers(creator.token) })).json();
  expect(fetched.data[0]).toMatchObject({ name: 'QA Tier', price: 3 });
});

test('wallet and payment failure paths never require a real wallet', async ({ request }) => {
  const data = await runtime(), primary = userFor(data, 'primary');
  const auth = await request.post(`${data.apiURL}/auth/login`, { data: { email: primary.email, password: data.password } });
  const token = (await auth.json()).token, headers = { authorization: `Bearer ${token}` };
  expect((await request.post(`${data.apiURL}/wallet/connect`, { headers, data: { address: '0x0000000000000000000000000000000000000001', signature: '0x00', challengeId: 'invalid' } })).status()).toBeGreaterThanOrEqual(400);
  expect((await request.post(`${data.apiURL}/tips/intents`, { headers, data: { creatorId: userFor(data, 'creator').id, amount: '1.00' } })).status()).toBe(503);
});

test('Release 1 private follows, friendship, Top Friends, and locked modules persist', async ({ request }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop-chromium', 'The API state transition is covered once per isolated run.');
  const data = await runtime();
  const login = async (role: string) => { const user = userFor(data, role); const response = await request.post(`${data.apiURL}/auth/login`, { data: { email: user.email, password: data.password } }); return { user, token: (await response.json()).token }; };
  const primary = await login('primary'), peer = await login('peer');
  const headers = (token: string) => ({ authorization: `Bearer ${token}` });
  expect((await request.put(`${data.apiURL}/users/profile`, { headers: headers(peer.token), data: { profilePrivacy: 'followers', isPrivate: true, dmAudience: 'friends', friendRequestAudience: 'everyone' } })).ok()).toBeTruthy();
  const follow = await request.post(`${data.apiURL}/users/${peer.user.id}/follow`, { headers: headers(primary.token) });
  expect(follow.status()).toBe(202); expect((await follow.json()).followStatus).toBe('requested');
  const followRequests = await (await request.get(`${data.apiURL}/social/follow-requests`, { headers: headers(peer.token) })).json();
  expect(followRequests.data).toHaveLength(1);
  expect((await request.patch(`${data.apiURL}/social/follow-requests/${followRequests.data[0]._id}`, { headers: headers(peer.token), data: { status: 'accepted' } })).ok()).toBeTruthy();
  const friendRequest = await request.post(`${data.apiURL}/social/friends/requests/${peer.user.id}`, { headers: headers(primary.token) });
  expect(friendRequest.status()).toBe(201);
  const incoming = await (await request.get(`${data.apiURL}/social/friends/requests`, { headers: headers(peer.token) })).json();
  expect((await request.patch(`${data.apiURL}/social/friends/requests/${incoming.data[0]._id}`, { headers: headers(peer.token), data: { status: 'accepted' } })).ok()).toBeTruthy();
  expect((await request.put(`${data.apiURL}/social/top-friends`, { headers: headers(peer.token), data: { friendIds: [primary.user.id] } })).ok()).toBeTruthy();
  const top = await (await request.get(`${data.apiURL}/social/top-friends/${peer.user.id}`, { headers: headers(primary.token) })).json();
  expect(top.data[0].friend._id).toBe(primary.user.id);
  const ruleResponse = await request.put(`${data.apiURL}/profiles/me/access-rules`, { headers: headers(peer.token), data: { rules: [{ name: 'Subscribers', presentation: 'locked_preview', expression: { op: 'predicate', type: 'subscribers' } }] } });
  const ruleId = (await ruleResponse.json()).data[0]._id;
  expect((await request.put(`${data.apiURL}/profiles/me/modules`, { headers: headers(peer.token), data: { modules: [{ type: 'bio', position: 0, enabled: true, config: {}, accessRuleId: ruleId }] } })).ok()).toBeTruthy();
  const publicProfile = await (await request.get(`${data.apiURL}/profiles/${peer.user.id}`, { headers: headers(primary.token) })).json();
  expect(publicProfile.data.modules[0]).toMatchObject({ type: 'bio', locked: true, presentation: 'locked_preview' });
  expect((await request.put(`${data.apiURL}/users/profile`, { headers: headers(peer.token), data: { profilePrivacy: 'public', isPrivate: false } })).ok()).toBeTruthy();
  const defaults = ['identity','bio','faction','top_friends','posts','media','links'].map((type, position) => ({ type, position, enabled: true, config: {} }));
  expect((await request.put(`${data.apiURL}/profiles/me/modules`, { headers: headers(peer.token), data: { modules: defaults } })).ok()).toBeTruthy();
});
