import { test, expect, login, runtime } from './fixtures';
test('Creator Studio activates the existing identity and survives refresh without fake analytics', async ({ monitoredPage: page }, testInfo) => {
  const data = await runtime();
  const name = `rc_${data.runId}_${testInfo.project.name.startsWith('mobile') ? 'm' : 'd'}`;
  const email = `${name}@example.invalid`, password = 'ReleaseCBrowserPass42';
  const registration = await page.request.post(`${data.apiURL}/auth/register`, { data: { username: name, email, password, faction: 'Unaffiliated' } });
  expect(registration.status()).toBe(201);
  await page.goto('/');
  await page.getByPlaceholder('your@email.com').fill(email);
  await page.getByPlaceholder('••••••••').fill(password);
  await page.getByRole('button', { name: 'ESTABLISH LINK' }).click();
  await expect(page.getByTitle('Notifications')).toBeVisible();
  const marker = `Release C browser content ${testInfo.project.name}`;
  const created = await page.evaluate(async ({ apiURL, marker }) => { const response = await fetch(`${apiURL}/posts`, { method: 'POST', headers: { Authorization: `Bearer ${localStorage.getItem('cdToken')}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ type: 'text', content: marker }) }); return response.status; }, { apiURL: (await runtime()).apiURL, marker });
  expect(created).toBe(201);
  await page.goto('/creator');
  await expect(page.getByRole('heading', { name: 'Creator Studio', exact: true })).toBeVisible();
  const activate = page.getByRole('button', { name: 'Activate Creator Mode', exact: true });
  await expect(activate).toBeVisible();
  await activate.click();
  await expect(page.getByRole('heading', { name: 'Audience overview' })).toBeVisible();
  await expect(page.getByText('Reach, impressions and growth analytics are not available.', { exact: false })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Monetization settings' })).toBeVisible();
  const row = page.locator('article').filter({ hasText: marker }).first();
  await row.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByLabel('Content title').fill(`${marker} edited`);
  await page.getByLabel('Content text').fill(`${marker} edited text`);
  await page.getByRole('button', { name: 'Save content', exact: true }).click();
  await expect(row).toContainText(`${marker} edited`);
  await row.getByRole('button', { name: 'Archive', exact: true }).click();
  await expect(row.getByRole('button', { name: 'Publish', exact: true })).toBeVisible();
  await row.getByRole('button', { name: 'Publish', exact: true }).click();
  await page.reload(); await expect(page.getByRole('heading', { name: 'Content management' })).toBeVisible();
  await expect(page.locator('article').filter({ hasText: `${marker} edited` }).first()).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.goto('/profile'); await expect(page.getByTestId('faction-contribution')).toContainText('Unaffiliated · Independent');
  await page.goto('/creators'); await expect(page.getByRole('heading', { name: 'Discover creators' })).toBeVisible();
});
test('ordinary accounts cannot read moderation queues and verification stays unavailable', async ({ monitoredPage: page }) => {
  await login(page);
  const results = await page.evaluate(async apiURL => {
    const headers = { Authorization: `Bearer ${localStorage.getItem('cdToken')}` };
    const queue = await fetch(`${apiURL}/moderation/queue`, { headers });
    const age = await (await fetch(`${apiURL}/age-verification/status`, { headers })).json();
    const config = await (await fetch(`${apiURL}/tips/contract/status`, { headers })).json();
    return { queue: queue.status, age: age.verification.age.verified, chain: config.contract.chainId, payments: config.contract.paymentExecutionEnabled };
  }, (await runtime()).apiURL || 'http://127.0.0.1:5001/api');
  expect(results).toEqual({ queue: 403, age: false, chain: 84532, payments: false });
});
